spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/mynotes
    username: "mynotes"
    password: "secret"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true